zoldyck/debah/urls.py
from django.urls import include, re_path,path
from . import views


app_name = 'debah'
urlpatterns = [
    path("list", views.list_abt , name="list_abt"),
    path("add_deba7",views.add_deba7,name='ajouter'),
    path("association/<int:d_id>" ,views.association , name="association"),
    path("association/association_org/<int:req_id>" , views.association_org, name="association_org"),
    path("association/edit/<int:abt_id>" ,views.edit , name="edit"),
    path("association/delete/<int:abt_id>" ,views.delete , name="delete"),

    


    ]

zoldyck/request/urls.py
from django.urls import include, re_path,path
from . import views


app_name = 'request'
urlpatterns = [
    path("request/", views.request_v , name="request_v"),
    path("all_request/", views.all_request , name="all_request"),
    path("confirm/", views.confirm_request , name="confirm"),

]

zoldyck/zoldyck/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import (
    home,
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls")),
    path('', include("debah.urls")),
    path('', include("request.urls")),

]

zoldyck/request/models.py
from email.headerregistry import Address
from django.db import models
from account.models import Account
from debah.models import deba7
import json
from django.core.validators import MaxValueValidator, MinValueValidator
file = open('request/wilayas.json',encoding="utf8")
data = json.load(file)
choix = []
choix_b = ['',[]]
for i in data:
	choix.append((i['name']))
	for j in i['dairats']:
		if 'baladyiats' in j:
			for k in j['baladyiats']:
				choix_b.append((i['name'],k['name']))
				#print((k['name']))
class request_s(models.Model):
	owner 		= models.OneToOneField(Account , on_delete=models.CASCADE)
	wilaya		= models.CharField(max_length=100)
	Address	    = models.CharField(max_length=100)
	taken       = models.BooleanField(default=False)
	# Create your models here.
 
class date_request(models.Model):
	organisation = models.ForeignKey(Account , on_delete=models.CASCADE , related_name="organisation",limit_choices_to={'is_org': True})
	debah		 = models.ForeignKey(deba7 , on_delete=models.CASCADE , related_name="debah")
	simple_user  = models.ForeignKey(Account , on_delete=models.CASCADE , related_name="simple_user" ,limit_choices_to={'is_org': False})
	jour         = models.IntegerField(default=1,validators=[MinValueValidator(1), MaxValueValidator(2)])
	date 		 = models.TimeField(blank=True , null=True)
	# deba7
	# org
		#user
		 #date
		  # 

zoldyck/request/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import request_s,date_request

class request_sform(forms.ModelForm):
    class Meta:
        model = request_s
        fields = ('owner','wilaya','Address')

zoldyck/request/views.py
from calendar import c
import re
from sys import orig_argv
from time import time
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect
from django.utils import timezone

from debah.models import deba7
from account.models import Account
from .models import date_request, request_s,choix_b,choix

from .forms import request_sform
# Create your views here.
def request_v(request):
	Owner = request.user
	if request.POST:
		wilaya = request.POST.get("wilaya")
		Address = request.POST.get("Adress")
		print(Owner,wilaya,Address)
		if wilaya and Address:
			print("here")
			req = request_s.objects.create(owner=Owner ,wilaya=wilaya ,Address=Address )
			req.save
			return redirect("account:home")
	return render (request, 'request/request_s.html',{"choix":choix})


def all_request(request):
	obj = request_s.objects.filter(taken=False)
	context = {'obj':obj}
	return render (request, "request/all_request.html" , context)


def confirm_request(request):	
	list = deba7.objects.filter(org=request.user)
	if request.method == 'POST':
		list = deba7.objects.filter(org=request.user)
		s = request.POST.get('d')
		s1 = request.POST.get('e')
		s2 = request.POST.get('f')
		s3 = request.POST.get('g')
		if s3 is not None:	
			d = date_request.objects.create(organisation=request.user,debah=get_object_or_404(deba7,pk=int(s3)),simple_user=get_object_or_404(Account,pk=2),date=timezone.now())
			print(s2)
	return render (request, 'request/confirm_request.html',{'list':list,'choix':choix})

zoldyck/templates/request/all_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>listofdemand</title>
</head>
<body>
    
    <section class=" text-center py-5" style="padding-left:650px;padding-top:100px" >
        <h1 style="margin-left:-25px;font-size:40px;color:#F6F8FF;">liste de demandes</h1>
    <div style="padding-top:10px;"><select name="wilaya" id="" style="height:40px;border-radius:20px;border:0px solid;width:250px;padding-left:10px;background-color:#F6F8FF"><option value="" style="height:40px;border-radius:20px;border:0px solid;width:250px;padding-left:10px;background-color:#F6F8FF">Choisir votre wilaya</option></select></div>
    <div style="padding-top:10px;"><input type="text" id="name" style="border-radius: 20px;height:40px;border: 0px solid;width:250px;padding-left:10px;background-color:#F6F8FF " name="name" placeholder="Email" ></div>
    </section>    
{% for req in obj %}
    <div class="container-fluid" style="padding-left:350px;padding-top:40px">
    <div style="width: 801px; height:203px;border-radius: 90px; border:5.5px solid #019267;padding-left:30px;">
        <div style="padding-top:30px">
        <p style="color:#019267; font-size:20px">Nom : {{req.owner.first_name}} {{req.owner.last_name}}</p>
        <p style="color:#019267; font-size:20px">Location: {{req.wilaya}} {{req.Address}}</p>
        <p style="color:#019267; font-size:20px">Numero de telephone:{{req.owner.phone_number}}</p>
        </div>
        <div style="padding-left:510px;margin-top:-175.5px;">
        <button style="color:#F6F8FF; font-size:40px;background-color:#019267;border-radius:90px;border:0px solid; width:290px;height:200px; "><a style="text-decoration: none; color:white;"href="{% url 'debah:association_org' req.id %}">allocation <br> un abatteur</a></button>
        </div>            
    </div>  
</div>
{% endfor %}


</body>
</html>

zoldyck/templates/request/confirm_request.html
{% load static %}
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    </head>
    <body>
<form method="POST">
	{%csrf_token %}
    <input type="text" name="d" placeholder="test">
    <select name="f" id="pet-select">
        {%for choice in choix %}
        <option value="{{deba7.id}}">{{choice}}</option>
        {%endfor%}
    </select>
    <select name="e" id="pet-select">
        {%for choice in choix_b %}
        <option value="{{deba7.id}}">{{choice}}</option>
        {%endfor%}
    </select>
    <select name="g" id="pet-select">
        {%for deba7 in list %}
        <option value="{{deba7.id}}">{{deba7.nom}} {{deba7.prenom}}</option>
        {%endfor%}
    </select>
<button type="submit">Confirmer </button>
</form>
</body>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'js/sel.js' %}"></script>

zoldyck/templates/request/request_s.html
{% extends 'navbarsign.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Demandepage</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/demandepage.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css" rel="stylesheet"/>
</head>
<body>


  <section class=" text-center py-5 " >
    <img src="{% static 'svg/demande_bg.svg' %}" alt="" style="position:absolute; bottom:0;right:0;z-index:-1;width:100vw;">
    <div  class="container py-1" style="padding:0 180px 0 0 ; margin:140px 0 0 0" >
        <form method="POST">
        {% csrf_token %}
      
        <div id="samy" class="d-flex align-items-center justify-content-center ">
          <div style="display:flex; flex-direction:column;"> 
            <h1 style="color: #F6F8FF;font-size:65px;font-weight:bold;padding-bottom:20px;" id="borhan">Demander un abatteur</h1>
            <div style="padding-top:30px;"><select name="wilaya" id="" style="height:55px;border-radius:20px;border:0px solid;width:350px;padding-left:10px;background-color:#F6F8FF">{% for vh in choix %}
              <option value="wilaya1" style="height:40px;border-radius:20px;border:0px solid;width:250px;padding-left:10px;background-color:#F6F8FF">{{vh}}</option>
{%endfor%}
           </select></div>

            <div style="padding-top:30px;"><input placeholder="Entre Votre Address" name="Adress" id="" style="height:55px;border-radius:20px;border:0px solid;width:350px;padding-left:10px;background-color:#F6F8FF"></div>
            <div style="padding-left:0px;padding-top:30px; ">
              <button type="submit"style="border-radius:20px; color:#F6F8FF;font-size:30px;padding-bottom:40px; border-color:#FFD365 ;width:350px; height:55px" id="btn1">
                  Demarer maintenant
             </button>
                          </form>

              </div>
              </div>
      </div></div></div>
            

 </section>

    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>
{%endblock%}