zoldyck/account/urls.py
from django.urls import include, re_path,path
from . import views


app_name = 'account'
urlpatterns = [
    path("", views.home , name="home"),
    path("signup/", views.signup, name="signup"),
    path("signin/", views.login_view, name="signin"),
    path("logout/", views.logout_view , name="logout"),
    path("joinus/", views.org_sign, name="join us")

]

zoldyck/debah/urls.py
from django.urls import include, re_path,path
from . import views


app_name = 'debah'
urlpatterns = [
    path("list", views.list_abt , name="list_abt"),
    path("add_deba7",views.add_deba7,name='ajouter'),
    path("association/<int:d_id>" ,views.association , name="association"),
    path("association/association_org/<int:req_id>" , views.association_org, name="association_org"),
    path("association/edit/<int:abt_id>" ,views.edit , name="edit"),
    path("association/delete/<int:abt_id>" ,views.delete , name="delete"),

    


    ]

zoldyck/zoldyck/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import (
    home,
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls")),
    path('', include("debah.urls")),
    path('', include("request.urls")),

]

zoldyck/templates/navbarsign.html
<!DOCTYPE html>
<html lang="en">
<head>
  {%load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>navbarsign</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
</head>
<body>
    {% if not request.user.is_org%}
    <nav class="navbar navbar-expand-lg navbar-light  fixed-top" style="background-color:#00C897;">
        <!-- Container wrapper -->
        <div class="container-fluid">
          <!-- Toggle button -->
          <button
            
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
          <i class="bi bi-list"></i>
          </button>
      
          <!-- Collapsible wrapper -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Navbar brand -->
            <a class="navbar-brand mt-2 mt-lg-0" href="#">
              <img
                src="{% static 'img/logo.svg' %}"
                height="25"
                loading="lazy"
              />
            </a>
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="padding-left:120px;">
              
             <li class="nav-item">
             <a class="nav-link" href="#" id="coloritems" style="padding-left:40px;">Accueil</a>
             </li>
            <li class="nav-item" >
              <a class="nav-link" href="#" id="coloritems"style="padding-left:40px;">Organisations</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="#" id="coloritems" style="padding-left:40px;">Faire Un Don</a>
             </li>
             <li class="nav-item">
              <a class="nav-link" href="#" id="coloritems" style="padding-left:40px;">FAQ</a>
             </li> 
             
            </ul>
            
            <!-- Left links -->
          </div>
          <!-- Collapsible wrapper -->
      
          <!-- Right elements -->
          <div class="d-flex align-items-center">
            <!--icon-->
           
            
            {% if not request.user.is_authenticated %}
            <button style="border-radius:20px; border-color:#FFD365 ">
                 <a style="text-decoration: none ;color: white; "href="/signin">sign in</a> 
            </button>
            <div style="padding-left:30px ; padding-right:20px">
            <button style="border-radius:20px; color:#FFD365; border-color:#FFD365" id="btn">
                  <a style="text-decoration: none ;color: white; "href="/signup">sign up</a>
           </button>
            </div>
            {% else %}
            <!-- Notifications -->
            <div class="dropdown">
              <a
                class="nav-link"
                href="#"
                id="navbarDropdownMenuLink"
                role="button"
                data-mdb-toggle="dropdown"
                aria-expanded="false"
              >
              <i class="bi bi-bell-fill" style="font-size: 7.5mm; color: #FFD365;"></i>
              </a>
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="dropdownMenuButton1"
              >
                <li>
                  <a class="dropdown-item" href="#">info</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">info2</a>
                </li>
                <li><hr class="dropdown-divider">
                </li>
                <li>
                  <a class="dropdown-item" href="#">info3</a>
                </li>
              </ul>
            </div>
            <!-- Avatar -->
            <div class="dropdown">
              <a
                class="dropdown-toggle d-flex align-items-center hidden-arrow"
                href="#"
                id="navbarDropdownMenuAvatar"
                role="button"
                data-mdb-toggle="dropdown"
                aria-expanded="false"
              >
              <i  class="bi bi-person-fill" style="font-size: 10mm; color: #FFD365;"></i>
              </a>
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="navbarDropdownMenuAvatar"
              >
                <li>
                  <a class="dropdown-item" href="#">idk</a>
                </li>
                <li>
                  <a class="dropdown-item" href="/logout">logout</a>
                </li>
              </ul>
            </div>


            {% endif %}
            
          </div>
          <!-- Right elements -->
        </div>
        <!-- Container wrapper -->
      </nav>

    {% else %}
     <nav class="navbar navbar-expand-lg navbar-light  fixed-top" style="background-color:#00C897;">
        <!-- Container wrapper -->
        <div class="container-fluid">
          <!-- Toggle button -->
          <button
            
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
          <i class="bi bi-list"></i>
          </button>
      
          <!-- Collapsible wrapper -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Navbar brand -->
            <a class="navbar-brand mt-2 mt-lg-0" href="#">
              <img
                src="./img/logo.svg"
                height="25"
                loading="lazy"
              />
            </a>
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="padding-left:120px;">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:home' %}" id="coloritems"  style="padding-left:40px">Accueil</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/all_request" id="coloritems"  style="padding-left:40px">Liste De Demandes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" id="coloritems"  style="padding-left:40px">Mon Profile</a>
              </li>
             
            </ul>
            
            <!-- Left links -->
          </div>
          <!-- Collapsible wrapper -->
      
          <!-- Right elements -->
          <div class="d-flex align-items-center">
            <!--icon-->
           
            
            <!-- Notifications -->
            <div class="dropdown">
              <a
                class="nav-link"
                href="#"
                id="navbarDropdownMenuLink"
                role="button"
                data-mdb-toggle="dropdown"
                aria-expanded="false"
              >
              <i class="bi bi-bell-fill" style="font-size: 7.5mm; color: #FFD365;"></i>
              </a>
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="dropdownMenuButton1"
              >
                <li>
                  <a class="dropdown-item" href="#">info</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">info2</a>
                </li>
                <li><hr class="dropdown-divider">
                </li>
                <li>
                  <a class="dropdown-item" href="#">info3</a>
                </li>
              </ul>
            </div>
            <!-- Avatar -->
            <div class="dropdown">
              <a
                class="dropdown-toggle d-flex align-items-center hidden-arrow"
                href="#"
                id="navbarDropdownMenuAvatar"
                role="button"
                data-mdb-toggle="dropdown"
                aria-expanded="false"
              >
              <i  class="bi bi-person-fill" style="font-size: 10mm; color: #FFD365;"></i>
              </a>
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="navbarDropdownMenuAvatar"
              >
                <li>
                  <a class="dropdown-item" href="#">idk</a>
                </li>
                <li>
                  <a class="dropdown-item" href="/logout">logout</a>
                </li>
              </ul>
            </div>
            
          </div>
          <!-- Right elements -->
        </div>
        <!-- Container wrapper -->
      </nav>
      {% endif %}
      {% block content %}
        
      {% endblock %}
      <script type="text/javascript"src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"></script>
 
</body>
</html>

zoldyck/templates/orgsign.html
{% extends 'navbarsign.html' %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donation</title>
    <link rel="stylesheet" href="{% static 'css/orgsign1.css' %}">
</head>
<body>


  
  
  <section class=" text-center py-5 " >
    <img src="{% static 'svg/demande_bg.svg' %}" alt="" style="position: absolute;bottom:0;right:0;z-index:-1;width:100vw;padding-top:20px">
    <div class="container py-1" style="width:80vw; height:500px;" >
      <form method="POST">
        {% csrf_token %}
        <div id="moh" class="d-flex align-items-center justify-content-center "style="padding:100px 400px 0 0;">
          <div style="display:flex; flex-direction:column;"> 
            <h1 style="color: #F6F8FF;padding:0 0 30px 50px;font-size:40px">rejoindre nous</h1>
            <div style="display:flex; flex-direction:column;"> 
              <div style="padding-top:10px;"><input type="text" id="name" style="border-radius: 20px;border: 0px solid;width:350px;height:55px;padding-left:10px; " name="first_name" placeholder="nom de l'association" ></div>
              <div style="padding-top:10px;"><input type="email" id="name" style="border-radius: 20px;border: 0px solid;width:350px;height:55px;padding-left:10px; " name="email" placeholder="email" ></div>
              <div style="padding-top:10px;"><input type="phone_number" id="name" style="border-radius: 20px;border: 0px solid;width:350px;height:55px;padding-left:10px; " name="name" placeholder="numero de telephone" ></div>
              <div style="padding-top:10px;"><input type="text" id="name" style="border-radius: 20px;border: 0px solid;width:350px;height:55px;padding-left:10px; " name="location" placeholder="adress" ></div>
              <div style="padding-top:10px;"><input type="password" id="name" style="border-radius: 20px;border: 0px solid;width:350px;height:55px;padding-left:10px;"  name="password1" placeholder="mot de passe" ></div>
              <div style="padding-top:10px;"><input type="password" id="name" style="border-radius: 20px;border: 0px solid;width:350px;height:55px;padding-left:10px;"  name="password2" placeholder="mot de passe" ></div>
              <div style="padding-left:0px;padding-top:20px;  ">
                <button type="submit" style="border-radius:20px; color:#F6F8FF; border-color:#FFD365 ;width:350px; height:55px" id="btn1">
                    appliquer
               </button>
               </form>
                </div>
            </div>
            
              </div>
        }
      </div></div>
            

 </section>
{%endblock%}








     









      
   










    
</body>
</html>